### PR TITLE
fix(menu/importieds): Transfer namespaces to document element for ied import

### LINKED ISSUE #1060: OpenSCD incorrectly handles namespaces in new project with import
**Describe the bug**

I did the following:

1. Create a new project
2. Add an icd file
3. Save and look at the output

The output looks like:

```xml
<SCL xmlns="http://www.iec.ch/61850/2003/SCL" version="2007" revision="B">
	<Header id="project"/>
	<Communication>
		<SubNetwork name="W01">
			<ConnectedAP iedName="XAT_SEL_411L_2" apName="S1">
				<Address>
					<P type="IP">0.0.0.0</P>
					<P type="IP-SUBNET">255.255.255.0</P>
					<P type="IP-GATEWAY">0.0.0.0</P>
					<P type="OSI-TSEL">0001</P>
					<P type="OSI-PSEL">00000001</P>
					<P type="OSI-SSEL">0001</P>
				</Address>
				<GSE ldInst="CFG" cbName="Ctl">
					<Address>
						<P type="MAC-Address">01-0C-CD-01-00-00</P>
						<P type="APPID">0000</P>
						<P type="VLAN-PRIORITY">4</P>
						<P type="VLAN-ID">3E8</P>
					</Address>
					<MinTime unit="s" multiplier="m">4</MinTime>
					<MaxTime unit="s" multiplier="m">1000</MaxTime>
				</GSE>
			</ConnectedAP>
		</SubNetwork>
	</Communication>
	<IED desc="ICD-411L-2S-R001-V0 for firmware R200-V0 or higher" name="XAT_SEL_411L_2" type="SEL_411L_2S" manufacturer="SEL" configVersion="ICD-411L-2S-R001-V0-Z200006-D20210701" originalSclVersion="2007" originalSclRevision="B">
		<Private type="SEL_IedInfo">
			<esel:ModelNumber xmlns:esel="http://www.selinc.com/2006/61850">SEL-411L-2S</esel:ModelNumber>
			<esel:ModelVersionMin xmlns:esel="http://www.selinc.com/2006/61850">R200</esel:ModelVersionMin>
			<esel:ClassFileVersion xmlns:esel="http://www.selinc.com/2006/61850">006</esel:ClassFileVersion>
			<esel:ClassFileDescription xmlns:esel="http://www.selinc.com/2006/61850" default="false">411L-2S - Sampled Values Subscriber R200-V0 or higher (Ed. 2 support, Controllable mod/beh)</esel:ClassFileDescription>
			<esel:IcdFilePath xmlns:esel="http://www.selinc.com/2006/61850">C:\Users\tilbrookm\AppData\Local\SEL\AcSELerator\Architect\Palette\SEL-411L-2_Template.CID</esel:IcdFilePath>
			<esel:CidSentTime xmlns:esel="http://www.selinc.com/2006/61850">07/20/2022 13:35:44</esel:CidSentTime>
		</Private>
```

Namespace declarations appear to be incorrectly.

* Each element within the `esel` namespace has a namespace declaration on the element.
* The SCL element does not have a namespace declaration for `esel`

This is on openscd.github.

I expect the namespace to be registered on the root element and not repeated.

The initial icd file appears correct:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<SCL xmlns:esel="http://www.selinc.com/2006/61850" version="2007" revision="B" xmlns="http://www.iec.ch/61850/2003/SCL">
  <Header id="XAT_Prot1" version="32" revision="1.0" toolID="AcSELerator Architect 2.3.9.1954" nameStructure="IEDName">
    <History>
      <Hitem version="32" revision="1.0" when="08/19/2022 13:51:55" who="SANC\tilbrookm" what="IED exported from Project XAT_Prot1" />
    </History>
  </Header>
  <Communication>
    <SubNetwork name="W01">
      <ConnectedAP iedName="XAT_SEL_411L_2" apName="S1">
        <Address>
          <P type="IP">0.0.0.0</P>
          <P type="IP-SUBNET">255.255.255.0</P>
          <P type="IP-GATEWAY">0.0.0.0</P>
          <P type="OSI-TSEL">0001</P>
          <P type="OSI-PSEL">00000001</P>
          <P type="OSI-SSEL">0001</P>
        </Address>
        <GSE ldInst="CFG" cbName="Ctl">
          <Address>
            <P type="MAC-Address">01-0C-CD-01-00-00</P>
            <P type="APPID">0000</P>
            <P type="VLAN-PRIORITY">4</P>
            <P type="VLAN-ID">3E8</P>
          </Address>
          <MinTime unit="s" multiplier="m">4</MinTime>
          <MaxTime unit="s" multiplier="m">1000</MaxTime>
        </GSE>
      </ConnectedAP>
    </SubNetwork>
  </Communication>
  <IED desc="ICD-411L-2S-R001-V0 for firmware R200-V0 or higher" name="XAT_SEL_411L_2" type="SEL_411L_2S" manufacturer="SEL" configVersion="ICD-411L-2S-R001-V0-Z200006-D20210701" originalSclVersion="2007" originalSclRevision="B">
    <Private type="SEL_IedInfo">
      <esel:ModelNumber>SEL-411L-2S</esel:ModelNumber>
      <esel:ModelVersionMin>R200</esel:ModelVersionMin>
      <esel:ClassFileVersion>006</esel:ClassFileVersion>
      <esel:ClassFileDescription default="false">411L-2S - Sampled Values Subscriber R200-V0 or higher (Ed. 2 support, Controllable mod/beh)</esel:ClassFileDescription>
      <esel:IcdFilePath>C:\Users\tilbrookm\AppData\Local\SEL\AcSELerator\Architect\Palette\SEL-411L-2_Template.CID</esel:IcdFilePath>
      <esel:CidSentTime>07/20/2022 13:35:44</esel:CidSentTime>
```

**To Reproduce**

[XAT_SEL-411L-2.ICD.zip](https://github.com/openscd/open-scd/files/9892620/XAT_SEL-411L-2.ICD.zip)

1. Using the attached icd file.
2. Create a new Edition 2 project.
3. Import the ICD file.
4. Save the project.
5. Open the scd file and examined the first 40 lines.
6. Observe that namespaces are incorrectly handled.

I think this must have happened recently...

### PR DESCRIPTION
**Pull request by danyill**
Closes #1060

### CODE REVIEW

File: src/menu/ImportIEDs.ts [hunk 1]
```diff
@@ -368,6 +368,31 @@ function isIedNameUnique(ied: Element, doc: Document): boolean {
...
+ * @param destElement - Element to transfer namespaces to
+ * @param sourceElement  - Element to transfer namespaces from
+ */
+function updateNamespaces(destElement: Element, sourceElement: Element) {
+  const attributes = Array.prototype.slice
+    .call(sourceElement.attributes)
+    .filter(attr => attr.name.startsWith('xmlns:'));
+
+  attributes.forEach(attr => {
+    if (!destElement.hasAttribute(attr.name)) {
```
Comment (pascalwilbrink) [inline src/menu/ImportIEDs.ts:382]: This if-statement could be transformed to a filter on top.


```
Array.prototype.slice
    .call(sourceElement.attributes)
    .filter(attr => attr.name.startsWith('xmlns:'))
    .filter(attr => !destElement.hasttribute(attr.name)
    .forEach((attr) => {
        destElement.setAttributeNS(
            'http://www.w3.org/2000/xmlns/',
            attr.name,
            attr.value
        );
    });
````

Comment (danyill) [reply src/menu/ImportIEDs.ts]: Seems very reasonable, thanks :bowing_man:
