### PR TITLE
fix(menu/importieds): allow import to new projects

### LINKED ISSUE #1011: Importing IED in new project fails
**Describe the bug**
Adding new IED in a project without `DataTypeTemplates` element does not work

**To Reproduce**
1. Create new project
2. Add some IED with the Import IED plugin
3. No IED is imported

**Additional context**
This bug was introduced with the performance improvement and synchronious loading of plugins. The import IED plugin does check whether `DataTypeTemplates` element is there. In this case a new actionElement is fired and the doc is updated. The doc the plugin is working with has then no documentElement anymore :(

### PR DESCRIPTION
**Pull request by JakobVogelsang**
Closes #1011 

See description of the bug in the issue.

### CODE REVIEW

File: src/menu/ImportIEDs.ts [hunk 1]
```diff
@@ -319,21 +319,42 @@ function addLNodeType(
 function addDataTypeTemplates(ied: Element, doc: XMLDocument): SimpleAction[] {
   const actions: (SimpleAction | undefined)[] = [];
 
+  const dataTypeTemplates = doc.querySelector(':root > DataTypeTemplates')
+    ? doc.querySelector(':root > DataTypeTemplates')!
+    : createElement(doc, 'DataTypeTemplates', {});
+
+  if (!dataTypeTemplates) {
```
Comment (dlabordus) [inline src/menu/ImportIEDs.ts:326]: There will always be a Element now, because you will query it of create it at line 322.

**Review by dlabordus — CHANGES_REQUESTED** [review]

File: src/menu/ImportIEDs.ts [hunk 2]
```diff
@@ -178,9 +178,9 @@ function hasConnectionToIed(type: Element, ied: Element): boolean {
 function addEnumType(
   ied: Element,
   enumType: Element,
-  doc: Document
+  parent: Element
```
[the remark this answers is not in the document]
Comment (JakobVogelsang) [reply src/menu/ImportIEDs.ts:181]: Very true! Thanks!

File: src/menu/ImportIEDs.ts (hunk 1 above)
Comment (JakobVogelsang) [reply src/menu/ImportIEDs.ts:326]: Very true! Thx

**Review by dlabordus — APPROVED** [review]
