### PR TITLE
Fix remove voltage level

### LINKED ISSUE #49: Undo delete VoltageLevel does not produce identical SCL
Undoing deletion of `VoltageLevel` does not lead to identical XML file. The `reference` in delete editor action is missing.

### PR DESCRIPTION
**Pull request by JakobVogelsang**
Closes #49

### CODE REVIEW

File: src/foundation.ts [hunk 1]
```diff
@@ -277,3 +277,23 @@ declare global {
...
+  string:
+    '([\u0009-\u000A]|[\u000D]|[\u0020-\u007E]|[\u0085]|[\u00A0-\uD7FF]|[\uE000-\uFFFD]|[\u{10000}\\-\u{10FFFF}])*',
+  normalizedString:
+    '([\u0020-\u007E]|[\u0085]|[\u00A0-\uD7FF]|[\uE000-\uFFFD]|[\u{10000}\\-\u{10FFFF}])*',
+  name: nameStartChar + ' (' + nameChar + ')*',
+  names: name + ' (\u0020 ' + name + ')*',
+  nmToke: '(' + nameChar + ')+',
+  nmTokens: nmToken + ' (\u0020 ' + nmToken + ')*',
+  decimal: '((-|\\+)?([0-9]+(.[0-9]*)?|.[0-9]+))',
+  min0decimal: '([0-9]+(.[0-9]*)?|.[0-9]+)',
```
Comment (c-dinkel) [inline src/foundation.ts:302]: Do we need to allow a leading `+` sign here?

**Review by c-dinkel — APPROVED** [review]
LGTM
