### PR TITLE
fix(validatetemplates): don't require "Oper" if ctlModel=status-only

### LINKED ISSUE #268: fix(validatetemplates): don't require "Oper" if ctlModel=status-only
There should already be some untested non-working code that's supposed to ensure this in `ValidateTemplates.ts` .

### PR DESCRIPTION
**Pull request by ca-d**
Closes #268 .

### CODE REVIEW

File: src/translations/de.ts [hunk 1]
```diff
@@ -59,12 +59,22 @@ export const de: Translations = {
...
+      valid: '{{ name }} erfolgreich validiert',
+      invalid: '{{ name }} Validierung fehlgeschlagen',
+      fatal: 'Fataler Validierungsfehler',
+      loadError: 'Konnte Schema {{ name }} nicht laden',
+    },
+    templates: {
+      title: 'Templates validieren',
+      mandatoryChild:
+        '{{ tag }} {{ id }} fehlt ein obligatorisches {{ childTag }}-Kind {{ childId }}',
+      missingCoDO: 'Control Datenobjekt vom Typ {{ type }} fehlt',
```
Comment (JakobVogelsang) [inline src/translations/de.ts:74]: I had it already incorrect and as you put so much effort into it: Cancel, SBO, SBOw and Oper are data attributes. I would suggest the following:
`Control-Service Datenattribut vom Typ {{type}} fehlt`

File: src/translations/en.ts [hunk 2]
```diff
@@ -90,12 +90,22 @@ export const en = {
...
+      valid: '{{ name }} validation successful',
+      invalid: '{{ name }} validation failed',
+      fatal: 'Fatal validation error',
+      loadError: 'Could not load schema {{ name }}',
+    },
+    templates: {
+      title: 'Validate templates',
+      mandatoryChild:
+        '{{ tag }} {{ id }} is missing mandatory child {{ childTag }} {{ childId }}',
+      missingCoDO: 'Control DO of type {{ type }} is missing',
```
Comment (JakobVogelsang) [inline src/translations/en.ts:105]: Would suggest here:
`Control service related data attribute {{type}} is missing`

File: src/translations/en.ts [hunk 3]
```diff
@@ -90,12 +90,22 @@ export const en = {
...
+      cannotValidate:
+        'Cannot validate {{ childTag }} {{ childId }} within {{ tag }} {{ id }}',
```
Comment (JakobVogelsang) [inline src/translations/en.ts:107]: How about:
`Cannot validate ... {{id}}:{{reasonCode}}`
This would allow adding something like ctlModel is not defined.

**Review by JakobVogelsang — COMMENTED** [review]
Thanks for the effort with this most likely annoying bug fix! 
Some strings can be more precise, but other than that, LGTM.
