### PR TITLE
fix(104): change options between different tis when selecting a doi

### LINKED ISSUE #1375: Protocol 104: Change options between different TI's when selecting a DOI
It is possible to be able to select multiple Ti's when adding a DOI. But all Ti's are bound to the same options.

When a DOI is a chosen a wizard pops up where a Ti number can be chosen. Below that are two switches that can be enabled and therefore used, or can be disabled, depending on if a Ti number allows that option. Right now it doesn't matter which Ti number you choose. If there's only 1 Ti number that allows an option, this option will be available for all Ti's in that DOI.

I would like to see a solution that the options are set for the chosen Ti number

### PR DESCRIPTION
**Pull request by Stef3st**
closes #1375

### CODE REVIEW

File: packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts [hunk 1]
```diff
@@ -218,13 +232,25 @@ export function createAddressesWizard(
...
+              const selectedTi = (<Select>e.target).selected!.value;
+              (<Switch>(
+                (<Select>e.target).parentElement!.querySelector(
+                  'mwc-switch[id="monitorInverted"]'
+                )
+              )).disabled = disableMonitorInvertedSwitch(
+                cdcProcessing.monitor,
+                selectedTi
+              );
+            }}
```
Comment (juancho0202) [inline packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts:253]: I would prefer if you move this chunk into a separate function for code readability, also verify that your querySelector has found something before trying to modify its disabled property to avoid a "cannot read property of undefined" scenario 👍

File: packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts [hunk 2]
```diff
@@ -167,6 +169,18 @@ export function disableInvertedSwitch(
   return disableSwitch;
 }
 
+export function disableMonitorInvertedSwitch(
+  tiInfo: Record<string, TiInformation>,
+  tiNumberInfo: string
+): boolean {
+  let disableSwitch = true;
+  const tiNumber = tiNumberInfo.split(' (')[0];
```
Comment (juancho0202) [inline packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts:177]: is this necessary? I thought the value in the dropdown was still set to only the tiNumber and that the split in your other PR was only to account for the maybeValue of the wizardtextfield

File: packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts [hunk 3]
```diff
@@ -167,6 +169,18 @@ export function disableInvertedSwitch(
   return disableSwitch;
 }
 
+export function disableMonitorInvertedSwitch(
```
Comment (juancho0202) [inline packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts:172]: Why not fixing this faulty behavior for all cases using the disableInvertedSwitch? This seems like code duplication

**Review by juancho0202 — CHANGES_REQUESTED** [review]

File: packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts (hunk 1 above)
Comment (Stef3st) [reply packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts:255]: Good catch! Will add that in

File: packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts (hunk 2 above)
Comment (Stef3st) [reply packages/open-scd/src/editors/protocol104/wizards/createAddresses.ts:179]: you're right, this really isn't necessary. Will remove that part!

**Review by juancho0202 — APPROVED** [review]
LGTM!
