### PR TITLE
fix(logging): do not log results of long running processes twice

### LINKED ISSUE #113: Validation result is logged twice
## How to reproduce

Open a project, thereby triggering validation.

## Expected result

The validation result should be logged only once.

## Actual result

The validation result gets logged twice.

### PR DESCRIPTION
**Pull request by JakobVogelsang**
close #113

### CODE REVIEW

File: src/Importing.ts [hunk 1]
```diff
@@ -248,7 +248,13 @@ export function Importing<TBase extends LitElementConstructor>(Base: TBase) {
...
           })
         );
-        throw new Error(get('import.log.loaderror'));
+        this.dispatchEvent(
+          newLogEvent({
+            kind: 'error',
+            title: get('import.log.loaderror'),
+          })
+        );
+        return;
```
Comment (c-dinkel) [inline src/Importing.ts:257]: Reject by `throw new Error();` or `throw new Error(get('import.log.loaderror'));`

File: src/Waiting.ts [hunk 2]
```diff
@@ -29,8 +29,8 @@ export function Waiting<TBase extends LitElementConstructor>(Base: TBase) {
       this.work.add(e.detail.promise);
       this.workDone = Promise.allSettled(this.work);
       await e.detail.promise.then(
```
Comment (c-dinkel) [inline src/Waiting.ts:31]: Instead use `promise.catch(reason => console.warn(reason))`

**Review by c-dinkel — CHANGES_REQUESTED** [review]

**Review by c-dinkel — APPROVED** [review]
LGTM
